name: Publish to Cargo

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: cargo

    steps:
      - uses: actions/checkout@v3

      - name: Cache deps
        id: cache-publish-action
        uses: actions/cache@v3
        env:
          cache-name: cache-publish-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.2.0

      - name: Install publish-action
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run: cargo install publish-action --version=0.2.0

      - name: Run publish-action
        id: publish-action
        run: publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
